# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.catbomb.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'catbomb', 'function_path': 'animated_java:catbomb/variants/default/apply'}
execute on passengers if entity @s[tag=aj.catbomb.bone.string2] run function animated_java:catbomb/variants/default/zzz/0
execute on passengers if entity @s[tag=aj.catbomb.bone.string] run function animated_java:catbomb/variants/default/zzz/1
execute on passengers if entity @s[tag=aj.catbomb.bone.flame] run function animated_java:catbomb/variants/default/zzz/2
execute on passengers if entity @s[tag=aj.catbomb.bone.bomb] run function animated_java:catbomb/variants/default/zzz/3