# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.meowster.root] run return 0
execute on passengers if entity @s[tag=aj.meowster.data] unless data entity @s {data:{rigHash: '4b192515ecb93e3eae1ebdfafff693f77d4c8f7ff1a907e69d8ccfdae3e2df0e'}} on vehicle run function animated_java:meowster/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1