# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.meowster.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
function #animated_java:meowster/as_root/pre_tick
execute if entity @s[tag=aj.meowster.animation.animation.model.new.playing] run function animated_java:meowster/animations/animation.model.new/zzz/on_tick
execute if entity @s[tag=aj.meowster.animation.idle.playing] run function animated_java:meowster/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.meowster.animation.walk.playing] run function animated_java:meowster/animations/walk/zzz/on_tick
execute if entity @s[tag=aj.meowster.animation.toss.playing] run function animated_java:meowster/animations/toss/zzz/on_tick
execute if entity @s[tag=aj.meowster.animation.true_idle.playing] run function animated_java:meowster/animations/true_idle/zzz/on_tick
execute if entity @s[tag=aj.meowster.animation.jump_or_dash.playing] run function animated_java:meowster/animations/jump_or_dash/zzz/on_tick
execute if entity @s[tag=aj.meowster.animation.d_or_j_end.playing] run function animated_java:meowster/animations/d_or_j_end/zzz/on_tick
execute if entity @s[tag=aj.meowster.animation.hammer.playing] run function animated_java:meowster/animations/hammer/zzz/on_tick
execute if entity @s[tag=aj.meowster.animation.die.playing] run function animated_java:meowster/animations/die/zzz/on_tick
execute if entity @s[tag=aj.meowster.animation.bread_eating.playing] run function animated_java:meowster/animations/bread_eating/zzz/on_tick
execute if entity @s[tag=aj.meowster.animation.spawn.playing] run function animated_java:meowster/animations/spawn/zzz/on_tick
execute on passengers if entity @s[tag=aj.meowster.data] run function animated_java:meowster/root/zzz/1
execute at @s on passengers run tp @s ~ ~ ~ ~ ~
function #animated_java:meowster/as_root/post_tick