# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.catbomb.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'catbomb', 'function_path': 'animated_java:catbomb/animations/throwed/next_frame'}
execute if score @s aj.throwed.frame matches 7.. run scoreboard players set @s aj.throwed.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.throwed.frame
execute at @s run function animated_java:catbomb/animations/throwed/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.throwed.frame 1