# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.catbomb.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'catbomb', 'function_path': 'animated_java:catbomb/animations/throwed/play'}
tag @s add aj.catbomb.animation.throwed.playing
scoreboard players set @s aj.throwed.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:catbomb/animations/throwed/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only