# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.meowster.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'meowster', 'function_path': 'animated_java:meowster/animations/pause_all'}
tag @s remove aj.meowster.animation.animation.model.new.playing
tag @s remove aj.meowster.animation.idle.playing
tag @s remove aj.meowster.animation.walk.playing
tag @s remove aj.meowster.animation.toss.playing
tag @s remove aj.meowster.animation.true_idle.playing
tag @s remove aj.meowster.animation.jump_or_dash.playing
tag @s remove aj.meowster.animation.d_or_j_end.playing
tag @s remove aj.meowster.animation.hammer.playing
tag @s remove aj.meowster.animation.die.playing
tag @s remove aj.meowster.animation.bread_eating.playing
tag @s remove aj.meowster.animation.spawn.playing