# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:meowster/animations/animation.model.new/zzz/apply_frame {frame: 2}
scoreboard players add @s aj.animation.model.new.frame 1