# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.meowster.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'meowster', 'function_path': 'animated_java:meowster/animations/jump_or_dash/next_frame'}
execute if score @s aj.jump_or_dash.frame matches 51.. run scoreboard players set @s aj.jump_or_dash.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.jump_or_dash.frame
execute at @s run function animated_java:meowster/animations/jump_or_dash/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.jump_or_dash.frame 1