# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.meowster.bone.hammer] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_hammer set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.meowster.bone.hand_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_hand_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.meowster.bone.lowerarm_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_lowerarm_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.meowster.bone.arm_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.meowster.bone.bread] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bread set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.meowster.bone.hand_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_hand_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.meowster.bone.lowerarm_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_lowerarm_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.meowster.bone.arm_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_arm_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.meowster.bone.uppertail] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_uppertail set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.meowster.bone.middletail] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_middletail set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.meowster.bone.tail] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_tail set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.meowster.bone.hair] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_hair set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.meowster.bone.ear_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ear_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.meowster.bone.ear_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ear_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.meowster.bone.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.meowster.bone.body] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.meowster.bone.shoe_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_shoe_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.meowster.bone.lowerleg_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_lowerleg_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.meowster.bone.leg_right] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.meowster.bone.shoe_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_shoe_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.meowster.bone.lowerleg_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_lowerleg_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.meowster.bone.leg_left] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_leg_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.meowster.bone.string2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_string2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.meowster.bone.string] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_string set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.meowster.bone.flame] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_flame set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.meowster.bone.bomb] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_bomb set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.meowster.bone.gg] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_gg set from storage aj:uuid main.out